guesswu/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from . import views

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.HomePageView.as_view(), name='home'),
    url(r'^accounts/signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^accounts/login/$', views.LoginView.as_view(), name='login'),
    url(r'^accounts/logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^play/', include('play.urls', namespace='play', app_name='play')),
)

play/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = patterns('',
    url(r'^new/(?P<difficulty>\d+)/$',
        login_required(views.NewGameView.as_view()),
        name='newgame'),
    url(r'^play/$',
        login_required(views.PlayGameView.as_view()),
        name='playgame'),
    url(r'^feat/(?P<pk>\d+)/$',
        login_required(views.PickFeatureView.as_view()),
        name='pickfeat'),
#    url(r'^end/$',
#        login_required(views.PlayGameView.as_view()),
#        name='end'),
)

templates/base.html
<!DOCTYPE html>
<!-- HTML5 Boilerplate -->
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->

<head>
	<meta charset="utf-8">
	<!-- Always force latest IE rendering engine & Chrome Frame -->
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

	<title>Guess Wu?</title>

	<meta name="description" content="from the glorious table game">
	<meta name="keywords" content="whatever, it may, be">
	<meta name="author" content="xyz">
	<meta http-equiv="cleartype" content="on">

	<link rel="shortcut icon" href="{{ STATIC_URL }}favicon.ico">

	<!-- Responsive and mobile friendly stuff -->
	<meta name="HandheldFriendly" content="True">
	<meta name="MobileOptimized" content="320">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="{{ STATIC_URL }}css/html5reset.css" media="all">
	<link rel="stylesheet" href="{{ STATIC_URL }}css/col.css" media="all">
	<link rel="stylesheet" href="{{ STATIC_URL }}css/2cols.css" media="all">
	<link rel="stylesheet" href="{{ STATIC_URL }}css/3cols.css" media="all">
	<link rel="stylesheet" href="{{ STATIC_URL }}css/4cols.css" media="all">
	<link rel="stylesheet" href="{{ STATIC_URL }}css/5cols.css" media="all">
	<link rel="stylesheet" href="{{ STATIC_URL }}css/6cols.css" media="all">
	<link rel="stylesheet" href="{{ STATIC_URL }}css/7cols.css" media="all">
	<link rel="stylesheet" href="{{ STATIC_URL }}css/8cols.css" media="all">
	<link rel="stylesheet" href="{{ STATIC_URL }}css/9cols.css" media="all">
	<link rel="stylesheet" href="{{ STATIC_URL }}css/10cols.css" media="all">
	<link rel="stylesheet" href="{{ STATIC_URL }}css/11cols.css" media="all">
	<link rel="stylesheet" href="{{ STATIC_URL }}css/12cols.css" media="all">

	<style type="text/css">

	/*  
	======================== 
	- Note: These styles are just to pretty the basic page up a bit.
	You should ignore these when copying and pasting into your site 
	because your stylesheet should take care of making it look pretty!
	======================== 
	*/
	body { padding:1em; font : 100%/1.4 'Helvetica Neue', arial, helvetica, helve, sans-serif; 	
 }
	h1 { font-size:2.0em; padding:0 0 .5em 0; }
	h2 { font-size:1.5em; }
	.header { padding:.5em 0; }
	.col { background: #ccc; padding:0.6em 0; text-align:center;}

	</style>
</head>
<body>
<div class="header">
	<h1><a href="{% url 'home' %}">Guess Wu?</a></h1>
</div>
<div class="section group">
	{% block actions %}{% endblock %}
</div>
{% block boards %}{% endblock %}
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% block actions %}
{% if user.is_authenticated %}
		<h2>Welcome {{ user.username|capfirst }}</h2>
		{% if continue_game %}
		  <h3><a href="{% url 'play:playgame' %}">Continue last game</a></h3>
		{% endif %}
		<h3>Start a new game:
		  <a href="{% url 'play:newgame' "0" %}">Easy</a>
		  or
		  <a href="{% url 'play:newgame' "1" %}">Hard</a>
		</h3>
{% else %}
		<h3>Welcome to the game</h3>
		<h3>Please <a href="{% url 'signup' %}">register</a>
			or <a href="{% url 'login' %}">login</a>
		</h3>
{% endif %}
{% endblock %}
{% block boards %}
{% if user.is_authenticated %}
		<div class="section group">
			<br>
			<h2>Hall of fame</h2>
			<table>
			<tr>
				<th>#&nbsp;</th>
				<th>Player&nbsp;</th>
				<th>Won&nbsp;</th>
				<th>Lost&nbsp;</th>
				<th>Draw&nbsp;</th>
			</tr>
			{% for pos, entry in hall_fame %}
			<tr>
				<td>{{ pos }}</td>
				<td>{{ entry.0|capfirst }}</td>
				<td>{{ entry.1 }}</td>
				<td>{{ entry.2 }}</td>
				<td>{{ entry.3 }}</td>
			</tr>
			{% endfor %}
			</table>
		</div>
{% endif %}
{% endblock %}